
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author maier
 */
public class InterfaceGraphique extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfaceGraphique.class.getName());
    
    private jeu JeuTHREES;
    private CelluleGraphique[][] cellules;
    private void miseAJourGrille() {
    for (int ligne = 0; ligne < 4; ligne++) {
        for (int colonne = 0; colonne < 4; colonne++) {
            cellules[ligne][colonne].miseAJourCellule();
        }
    }
    if (JeuTHREES.estFini()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Partie terminée !");
    }
    score.setText("Score : " + JeuTHREES.Score());
    nbcoups.setText("Nombre de Coups:" + JeuTHREES.coups());

    
}

    /**
     * Creates new form InterfaceGraphique
     */
    public InterfaceGraphique() {
        initComponents();
        this.getContentPane().setBackground(new java.awt.Color(153, 204, 255));
        
        JeuTHREES = new jeu();
        cellules = new CelluleGraphique[4][4];

        panneauGrille.setLayout(new java.awt.GridLayout(4, 4));

        for (int ligne = 0; ligne < 4; ligne++) {
            for (int colonne = 0; colonne < 4; colonne++) {
                CelluleGraphique c = new CelluleGraphique(JeuTHREES, ligne, colonne);
                cellules[ligne][colonne] = c;
                panneauGrille.add(c);
            }
        }
        miseAJourGrille();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneauGrille = new javax.swing.JPanel();
        btnDroite = new javax.swing.JButton();
        btnHaut = new javax.swing.JButton();
        btnBas = new javax.swing.JButton();
        btnGauche = new javax.swing.JButton();
        score = new javax.swing.JLabel();
        nbcoups = new javax.swing.JLabel();
        Menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(100, 100));

        panneauGrille.setBackground(new java.awt.Color(255, 255, 204));
        panneauGrille.setForeground(new java.awt.Color(255, 255, 204));
        panneauGrille.setPreferredSize(new java.awt.Dimension(300, 300));
        panneauGrille.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnDroite.setText("→ ");
        btnDroite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDroiteActionPerformed(evt);
            }
        });

        btnHaut.setText("↑");
        btnHaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHautActionPerformed(evt);
            }
        });

        btnBas.setText("↓");
        btnBas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBasActionPerformed(evt);
            }
        });

        btnGauche.setText("←");
        btnGauche.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGaucheActionPerformed(evt);
            }
        });

        score.setText("SCORE");

        nbcoups.setText("COUPS");

        Menu.setText("MENU");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(btnGauche, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(panneauGrille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(btnHaut, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(btnBas, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDroite)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(score, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nbcoups, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnHaut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panneauGrille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnGauche)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBas)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(score)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nbcoups)
                .addGap(106, 106, 106)
                .addComponent(btnDroite)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Menu)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHautActionPerformed
        // TODO add your handling code here:
        JeuTHREES.jouerHaut();   // étape 4
        miseAJourGrille(); 
    }//GEN-LAST:event_btnHautActionPerformed

    private void btnDroiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDroiteActionPerformed
        // TODO add your handling code here:
        JeuTHREES.jouerDroite();   // étape 4
        miseAJourGrille(); 
    }//GEN-LAST:event_btnDroiteActionPerformed

    private void btnBasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBasActionPerformed
        // TODO add your handling code here:
        JeuTHREES.jouerBas();   // étape 4
        miseAJourGrille(); 
    }//GEN-LAST:event_btnBasActionPerformed

    private void btnGaucheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGaucheActionPerformed
        // TODO add your handling code here:
        JeuTHREES.jouerGauche();  
        miseAJourGrille(); 
    }//GEN-LAST:event_btnGaucheActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
    // TODO add your handling code here:
    int choix = JOptionPane.showConfirmDialog(
        this,
        "Retourner au menu ? La partie sera perdue.",
        "Confirmation",
        JOptionPane.YES_NO_OPTION
    );

    if (choix == JOptionPane.YES_OPTION) {
        new InterfaceAcceuil().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_MenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfaceGraphique().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Menu;
    private javax.swing.JButton btnBas;
    private javax.swing.JButton btnDroite;
    private javax.swing.JButton btnGauche;
    private javax.swing.JButton btnHaut;
    private javax.swing.JLabel nbcoups;
    private javax.swing.JPanel panneauGrille;
    private javax.swing.JLabel score;
    // End of variables declaration//GEN-END:variables
}
